import Head from "next/head";
import { Carousel } from "@/components/Carousel2";
import { SectionStory } from "@/components/SectionStory";
import { MobileAppCTA } from "@/components/MobileAppCTA";
import { CTANewsletter } from "@/components/CTANewsletter";
import { MtnCardWrapper } from "@/stories/MtnCardWrapper";
import { useEffect } from "react";
import { CTAText } from "@/components/CTAText";
import { Hero } from "@/stories/Hero";
import { heroImage } from "@/util/config";
import { Test } from "@/components/Test";
import { CardContainer } from "@/components/CardContainer";
import { MountainLineFooter } from "@/stories/assets/mtn_line_footer_1";
import { HeroImgTextCenter } from "@/components/HeroImgTextCenter";
import { heroContent } from "@/util/data";

export default function Home() {
  useEffect(() => {
    const elements = document.querySelectorAll(".scroll-animate");

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          entry.target.classList.toggle("show", entry.isIntersecting);
          if (entry.isIntersecting) observer.unobserve(entry.target);
        });
      },
      {
        threshold: 0.6,
      }
    );

    elements.forEach((el) => {
      observer.observe(el);
    });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {/* <Test /> */}
        <HeroImgTextCenter data={heroContent} />
        {/* <Hero img={heroImage} tint /> */}
        <MobileAppCTA />
        <CardContainer />
        <SectionStory />
        <MtnCardWrapper scroll dark />
        <CTANewsletter />
      </main>
    </>
  );
}
