import Head from "next/head";

export default function OurStoryPage() {
  return (
    <>
      <Head>
        <title>Our Story</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Our Story Page</h1>
      </main>
    </>
  );
}
